apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: ajay4uu/nodeapp
          ports:
            - name: http
              containerPort: 80